baseURL = 'https://az-certified.com/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
languageCode = 'en-us'
title = 'Azure Certified'

theme = 'hugo-theme-relearn'

[minify]
disableHTML = true
