baseURL = 'https://azcertified.com/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
languageCode = 'en-us'
title = 'AZ Certified'

theme = 'hugo-theme-relearn'

[minify]
disableHTML = true
