[[shortcuts]]
name = "<i class='fab fa-github'></i> Repository"
identifier = "ds"
url = "https://github.com/marconipoveda/azcertified"
weight = 10

[[shortcuts]]
name = "<i class='fas fa-hand-holding-heart'></i> Contribute"
identifier = "contribute"
url = "https://github.com/marconipoveda/azcertified/contribute"
weight = 20

[[shortcuts]]
name = "<i class='fas fa-fw fa-calendar'></i> Official Site"
identifier = "Certifications"
url = "https://learn.github.com/certifications"
weight = 30

